// Icon mapping - centralized Lucide icon registry
// Maps semantic icon names to Lucide React components
// Add new icons here and use them via <Icon name="..." />

import {
  BookOpen,
  Monitor,
  RefreshCw,
  Lock,
  Flame,
  Bookmark,
  Settings,
  Shield,
  LogOut,
  AlertTriangle,
  Search,
  ChevronRight,
  ChevronLeft,
  ArrowRight,
  Menu,
  X,
  User,
  Mail,
  Globe,
  Moon,
  Sun,
  Check,
  XCircle,
  AlertCircle,
  Info,
  Star,
  Heart,
  Share2,
  ExternalLink,
  Clock,
  Calendar,
  FileText,
  FolderOpen,
  Tag,
  TrendingUp,
  Users,
  BarChart3,
  LayoutDashboard,
  Eye,
  Edit,
  Trash2,
  Plus,
  Minus,
  Home,
  ChevronDown,
  ChevronUp,
  CreditCard,
  Zap,
  Code,
  Cpu,
  Terminal,
  Database,
  Cloud,
  GitBranch,
  MessageSquare,
  Send,
  Bell,
  HelpCircle,
  Phone,
  MapPin,
  Link as LinkIcon,
  Play,
  Pause,
  Download,
  Upload,
  Filter,
  SortAsc,
  Grid,
  List,
  Compass,
  Sparkles,
  Rocket,
  Target,
  Lightbulb,
  Wrench,
  BookMarked,
  GraduationCap,
  Award,
  ShieldCheck,
  Wallet,
  Receipt,
} from 'lucide-react';

export const iconMap = {
  // Navigation & Layout
  'book': BookOpen,
  'book-marked': BookMarked,
  'compass': Compass,
  'home': Home,
  'menu': Menu,
  'x': X,
  'search': Search,
  'globe': Globe,

  // Actions
  'chevron-right': ChevronRight,
  'chevron-left': ChevronLeft,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'arrow-right': ArrowRight,
  'external-link': ExternalLink,
  'plus': Plus,
  'minus': Minus,
  'edit': Edit,
  'trash': Trash2,
  'download': Download,
  'upload': Upload,
  'filter': Filter,
  'share': Share2,
  'send': Send,

  // Content & Knowledge
  'file-text': FileText,
  'folder': FolderOpen,
  'bookmark': Bookmark,
  'tag': Tag,
  'code': Code,
  'terminal': Terminal,
  'database': Database,
  'git-branch': GitBranch,

  // Status & Feedback
  'lock': Lock,
  'unlock': Lock, // alias
  'flame': Flame,
  'alert-triangle': AlertTriangle,
  'alert-circle': AlertCircle,
  'check': Check,
  'x-circle': XCircle,
  'info': Info,
  'sparkles': Sparkles,
  'rocket': Rocket,
  'target': Target,
  'lightbulb': Lightbulb,
  'wrench': Wrench,
  'star': Star,
  'heart': Heart,

  // Dashboard & Analytics
  'dashboard': LayoutDashboard,
  'bar-chart': BarChart3,
  'trending-up': TrendingUp,
  'eye': Eye,
  'users': Users,
  'cpu': Cpu,
  'cloud': Cloud,

  // User & Auth
  'user': User,
  'settings': Settings,
  'shield': Shield,
  'shield-check': ShieldCheck,
  'log-out': LogOut,
  'mail': Mail,

  // Time & Date
  'clock': Clock,
  'calendar': Calendar,

  // Messaging & Help
  'message': MessageSquare,
  'help': HelpCircle,
  'phone': Phone,
  'map-pin': MapPin,

  // Finance
  'credit-card': CreditCard,
  'wallet': Wallet,
  'receipt': Receipt,

  // Features
  'zap': Zap,
  'refresh': RefreshCw,
  'monitor': Monitor,
  'graduation-cap': GraduationCap,
  'award': Award,

  // Theme
  'moon': Moon,
  'sun': Sun,

  // List/Grid
  'grid': Grid,
  'list': List,

  // Media
  'play': Play,
  'pause': Pause,
  'link': LinkIcon,
  'bell': Bell,
};

export type IconName = keyof typeof iconMap;
