/**
 * Codcompass 2.0 KB taxonomy: aligned with `Codcompass_Knowledge_Base/` vault layout + lib/kb-nav-tree.ts.
 * Used only for Knowledge Base articles (`Article` + `Category`)—not blog posts (`BlogPost` + `BlogCategory`).
 * Slugs stay stable where possible for DB joins; merged lanes use new canonical slugs (run remap script after deploy).
 */

import type { CategoryInfo } from '@/lib/category-types';

/** Primary section when slug has no explicit mapping. */
export const CC20_DEFAULT_SECTION_SLUG = 'cc20-4-1-tools-efficiency';

/** Browse/filter categories (vault-aligned IA). */
export const CC20_SECTIONS: CategoryInfo[] = [
  // ─── AI_Engineering ───
  {
    slug: 'cc20-1-1-ai-agent-development',
    name: 'AI Agents & Orchestration',
    nameZh: 'AI Agents & Orchestration',
    description: 'Agents, tooling, orchestration, evaluation',
    descriptionEn: 'Agents, tooling, orchestration, evaluation',
    icon: '🤖',
    color: 'from-violet-500 to-purple-600',
  },
  {
    slug: 'cc20-1-2-enterprise-rag',
    name: 'Enterprise RAG & Knowledge Engines',
    nameZh: 'Enterprise RAG & Knowledge Engines',
    description: 'Retrieval architecture, grounding economics, pipeline governance',
    descriptionEn: 'Retrieval architecture, grounding economics, pipeline governance',
    icon: '🤖',
    color: 'from-purple-500 to-indigo-600',
  },
  {
    slug: 'cc20-1-3-local-llm',
    name: 'Local LLM Deployment & Optimization',
    nameZh: 'Local LLM Deployment & Optimization',
    description: 'Sovereign inference, hardware co-design, quantization trade-offs',
    descriptionEn: 'Sovereign inference, hardware co-design, quantization trade-offs',
    icon: '🤖',
    color: 'from-fuchsia-500 to-pink-600',
  },
  {
    slug: 'cc20-1-4-ai-productization',
    name: 'AI Productionization & Commercialization',
    nameZh: 'AI Productionization & Commercialization',
    description: 'SLIs, packaging, margin risk, and durable AI products',
    descriptionEn: 'SLIs, packaging, margin risk, and durable AI products',
    icon: '🤖',
    color: 'from-indigo-500 to-blue-600',
  },
  // ─── System_Evolution ───
  {
    slug: 'cc20-2-1-architecture-transformation',
    name: 'Architecture Modernization & Transformation',
    nameZh: 'Architecture Modernization & Transformation',
    description: 'Strangler paths, migration portfolios, reversible bets',
    descriptionEn: 'Strangler paths, migration portfolios, reversible bets',
    icon: '🏗️',
    color: 'from-slate-500 to-zinc-600',
  },
  {
    slug: 'cc20-2-scalable-backend-systems',
    name: 'Scalable Backend Systems',
    nameZh: 'Scalable Backend Systems',
    description: 'Application platforms, data planes, integration, performance ceilings',
    descriptionEn: 'Application platforms, data planes, integration, performance ceilings',
    icon: '🏗️',
    color: 'from-blue-600 to-cyan-700',
  },
  {
    slug: 'cc20-2-4-devops-iac',
    name: 'DevOps & Infrastructure as Code',
    nameZh: 'DevOps & Infrastructure as Code',
    description: 'Delivery trust, declarative estates, operational platforms',
    descriptionEn: 'Delivery trust, declarative estates, operational platforms',
    icon: '🏗️',
    color: 'from-orange-600 to-red-600',
  },
  // ─── Platform_Product_Engineering ───
  {
    slug: 'cc20-3-3-one-person-os',
    name: 'One-Person Business Operating System',
    nameZh: 'One-Person Business Operating System',
    description: 'Finance rhythm, ops automation, workflow systems under constraint',
    descriptionEn: 'Finance rhythm, ops automation, workflow systems under constraint',
    icon: '💰',
    color: 'from-lime-600 to-green-700',
  },
  {
    slug: 'cc20-3-1-digital-asset-matrix',
    name: 'Automated Product Delivery',
    nameZh: 'Automated Product Delivery',
    description: 'Product matrices, reusable delivery rails, packaging leverage',
    descriptionEn: 'Product matrices, reusable delivery rails, packaging leverage',
    icon: '💰',
    color: 'from-amber-500 to-yellow-600',
  },
  {
    slug: 'cc20-3-2-growth-traffic',
    name: 'Digital Operations Automation',
    nameZh: 'Digital Operations Automation',
    description: 'GEO/SEO loops, measurable acquisition, automation guardrails',
    descriptionEn: 'GEO/SEO loops, measurable acquisition, automation guardrails',
    icon: '💰',
    color: 'from-emerald-500 to-teal-600',
  },
  // ─── Developer_Mastery ───
  {
    slug: 'cc20-4-1-tools-efficiency',
    name: 'Productivity & Workflow Engineering',
    nameZh: 'Productivity & Workflow Engineering',
    description: 'Environment design, templates, leverage without fragility',
    descriptionEn: 'Environment design, templates, leverage without fragility',
    icon: '📦',
    color: 'from-sky-500 to-blue-600',
  },
  {
    slug: 'cc20-4-2-code-quality',
    name: 'Systematic Learning & Methodology',
    nameZh: 'Systematic Learning & Methodology',
    description: 'Security bar, performance hygiene, repeatable craft',
    descriptionEn: 'Security bar, performance hygiene, repeatable craft',
    icon: '📦',
    color: 'from-teal-500 to-cyan-600',
  },
  {
    slug: 'cc20-4-3-reusable-components',
    name: 'Cognitive & Architectural Thinking',
    nameZh: 'Cognitive & Architectural Thinking',
    description: 'Boundaries, libraries, composability as architecture',
    descriptionEn: 'Boundaries, libraries, composability as architecture',
    icon: '📦',
    color: 'from-indigo-500 to-sky-600',
  },
  // ─── Cross_Cutting_Concerns ───
  {
    slug: 'cc20-cross-security-compliance',
    name: 'Security & Compliance',
    nameZh: 'Security & Compliance',
    description: 'Trust boundaries, evidence-ready controls, least privilege lifecycle',
    descriptionEn: 'Trust boundaries, evidence-ready controls, least privilege lifecycle',
    icon: '🛡️',
    color: 'from-red-700 to-rose-900',
  },
  {
    slug: 'cc20-cross-cost-sustainability',
    name: 'Cost Engineering & Sustainability',
    nameZh: 'Cost Engineering & Sustainability',
    description: 'Unit economics, capacity guardrails, operational sustainability',
    descriptionEn: 'Unit economics, capacity guardrails, operational sustainability',
    icon: '⚖️',
    color: 'from-emerald-700 to-teal-900',
  },
  {
    slug: 'cc20-cross-observability',
    name: 'Observability & Intelligent Monitoring',
    nameZh: 'Observability & Intelligent Monitoring',
    description: 'SLOs, signals-to-decisions, alert hygiene and narrative traces',
    descriptionEn: 'SLOs, signals-to-decisions, alert hygiene and narrative traces',
    icon: '📡',
    color: 'from-sky-700 to-blue-900',
  },
  // ─── Insights_Methodology ───
  {
    slug: 'cc20-5-2-book-notes',
    name: 'Book Reviews',
    nameZh: 'Book Reviews',
    description: 'Compressed canon, mechanisms over slogans, transfer notes',
    descriptionEn: 'Compressed canon, mechanisms over slogans, transfer notes',
    icon: '📖',
    color: 'from-stone-500 to-neutral-700',
  },
  {
    slug: 'cc20-5-deep-dives',
    name: 'Deep Dives',
    nameZh: 'Deep Dives',
    description: 'Strategy signals, cases, field notes, vertical realism',
    descriptionEn: 'Strategy signals, cases, field notes, vertical realism',
    icon: '📖',
    color: 'from-neutral-500 to-stone-600',
  },
  {
    slug: 'cc20-insights-research-notes',
    name: 'Research Notes',
    nameZh: 'Research Notes',
    description: 'Versioned hypotheses, replication-aware sourcing',
    descriptionEn: 'Versioned hypotheses, replication-aware sourcing',
    icon: '📖',
    color: 'from-zinc-700 to-stone-900',
  },
  // ─── Archive / References ──
  {
    slug: 'cc20-archive',
    name: 'Archive',
    nameZh: 'Archive',
    description: 'Superseded paths kept for traceability—not active recommendation',
    descriptionEn: 'Superseded paths kept for traceability—not active recommendation',
    icon: '️',
    color: 'from-zinc-600 to-zinc-900',
  },
  {
    slug: 'cc20-references',
    name: 'References',
    nameZh: 'References',
    description: 'Standards, papers, specs—pinned evidence for claims',
    descriptionEn: 'Standards, papers, specs—pinned evidence for claims',
    icon: '🔗',
    color: 'from-slate-600 to-neutral-900',
  },
  // ─── Legacy categories (still have articles in DB) ───
  {
    slug: 'frontend',
    name: 'Frontend Frameworks',
    nameZh: '前端框架',
    description: 'React, Vue, Next.js, and modern frontend development',
    descriptionEn: 'React, Vue, Next.js, and modern frontend development',
    icon: '🎨',
    color: 'from-pink-500 to-rose-600',
  },
  {
    slug: 'ai-llm',
    name: 'AI & LLM',
    nameZh: 'AI & LLM',
    description: 'Large language models, prompt engineering, model training',
    descriptionEn: 'Large language models, prompt engineering, model training',
    icon: '',
    color: 'from-violet-600 to-purple-700',
  },
  {
    slug: 'backend',
    name: 'Backend Technologies',
    nameZh: '后端技术',
    description: 'Server-side development, microservices, APIs',
    descriptionEn: 'Server-side development, microservices, APIs',
    icon: '⚙️',
    color: 'from-blue-600 to-indigo-700',
  },
  {
    slug: 'security',
    name: 'Security',
    nameZh: 'Security',
    description: 'Application security, authentication, best practices',
    descriptionEn: 'Application security, authentication, best practices',
    icon: '🔒',
    color: 'from-red-600 to-red-800',
  },
  {
    slug: 'devops',
    name: 'DevOps',
    nameZh: 'DevOps',
    description: 'CI/CD, containers, infrastructure automation',
    descriptionEn: 'CI/CD, containers, infrastructure automation',
    icon: '🚀',
    color: 'from-orange-500 to-orange-700',
  },
  {
    slug: 'mobile',
    name: 'Mobile Development',
    nameZh: '移动开发',
    description: 'iOS, Android, React Native, Flutter',
    descriptionEn: 'iOS, Android, React Native, Flutter',
    icon: '📱',
    color: 'from-green-500 to-emerald-600',
  },
  {
    slug: 'cc20-2-2-dotnet-csharp',
    name: '.NET / C# Advanced Development',
    nameZh: '.NET / C# Advanced Development',
    description: 'ASP.NET, Blazor, C# patterns and performance',
    descriptionEn: 'ASP.NET, Blazor, C# patterns and performance',
    icon: '💻',
    color: 'from-purple-500 to-indigo-600',
  },
  {
    slug: 'product',
    name: 'Product & Entrepreneurship',
    nameZh: '产品/创业',
    description: 'Product strategy, startup growth, user research',
    descriptionEn: 'Product strategy, startup growth, user research',
    icon: '💡',
    color: 'from-yellow-500 to-amber-600',
  },
  {
    slug: 'api',
    name: 'API Development',
    nameZh: 'API 开发',
    description: 'REST, GraphQL, API design and documentation',
    descriptionEn: 'REST, GraphQL, API design and documentation',
    icon: '🔌',
    color: 'from-cyan-500 to-blue-600',
  },
  {
    slug: 'database',
    name: 'Database',
    nameZh: 'Database',
    description: 'SQL, NoSQL, data modeling, performance tuning',
    descriptionEn: 'SQL, NoSQL, data modeling, performance tuning',
    icon: '🗃️',
    color: 'from-teal-500 to-cyan-600',
  },
  {
    slug: 'cc20-5-1-industry-insights',
    name: 'Industry Trends & Insights',
    nameZh: '行业趋势与洞察',
    description: 'Technology trends, CIO insights, market analysis',
    descriptionEn: 'Technology trends, CIO insights, market analysis',
    icon: '',
    color: 'from-slate-500 to-gray-600',
  },
  {
    slug: 'cc20-5-3-case-studies',
    name: 'Case Studies & Retrospectives',
    nameZh: '案例研究与回顾',
    description: 'Real-world project post-mortems and lessons learned',
    descriptionEn: 'Real-world project post-mortems and lessons learned',
    icon: '📋',
    color: 'from-stone-500 to-zinc-600',
  },
  {
    slug: 'cc20-2-3-data-architecture',
    name: 'Data Architecture & Intelligent Systems',
    nameZh: '数据架构与智能系统',
    description: 'Data pipelines, warehousing, analytics architecture',
    descriptionEn: 'Data pipelines, warehousing, analytics architecture',
    icon: '📈',
    color: 'from-indigo-500 to-violet-600',
  },
  {
    slug: 'cc20-3-4-personal-branding',
    name: 'Personal Branding & Monetization',
    nameZh: '个人品牌与变现',
    description: 'Building audience, content strategy, creator economy',
    descriptionEn: 'Building audience, content strategy, creator economy',
    icon: '✨',
    color: 'from-amber-500 to-orange-600',
  },
];

const T = {
  aiAgents: 'cc20-1-1-ai-agent-development',
  rag: 'cc20-1-2-enterprise-rag',
  localLlm: 'cc20-1-3-local-llm',
  aiProd: 'cc20-1-4-ai-productization',
  arch: 'cc20-2-1-architecture-transformation',
  scalableBackend: 'cc20-2-scalable-backend-systems',
  devops: 'cc20-2-4-devops-iac',
  onePersonOs: 'cc20-3-3-one-person-os',
  autoProduct: 'cc20-3-1-digital-asset-matrix',
  digitalOps: 'cc20-3-2-growth-traffic',
  tools: 'cc20-4-1-tools-efficiency',
  methodology: 'cc20-4-2-code-quality',
  cognitive: 'cc20-4-3-reusable-components',
  deepDives: 'cc20-5-deep-dives',
  bookReviews: 'cc20-5-2-book-notes',
  researchNotes: 'cc20-insights-research-notes',
} as const;

/** Explicit article slug → CC20 section slug (Published KB content). */
const ARTICLE_CC20_SECTION: Record<string, string> = {
  // ─── AI / ML ───
  'ai-rag-complete-guide': T.rag,
  'ai-vector-databases': T.rag,
  'ai-fine-tuning-guide': T.localLlm,
  'ai-agents-langchain': T.aiAgents,

  // ─── Scalable backend / data ───
  'postgresql-performance': T.scalableBackend,
  'database-design-patterns': T.scalableBackend,
  'redis-caching-strategies': T.scalableBackend,
  'mongodb-vs-postgresql': T.scalableBackend,

  // ─── DevOps ───
  'docker-compose-guide': T.devops,
  'github-actions-ci-cd': T.devops,
  'linux-essentials-devops': T.devops,
  'monitoring-observability': T.devops,

  // ─── Methodology lane (security, TS, Node craft) ───
  'web-security-essentials': T.methodology,
  'jwt-authentication': T.methodology,
  'api-security-guide': T.methodology,
  'oauth2-guide': T.methodology,
  'typescript-generics-advanced': T.methodology,
  'typescript-migration-guide': T.methodology,
  'typescript-narrowing': T.methodology,
  'nodejs-best-practices': T.methodology,
  'nodejs-streams': T.methodology,

  // ─── Legacy KB nav slugs ───
  'rag-intro': T.rag,
  'rag-architecture': T.rag,
  'rag-indexing': T.rag,
  'rag-retrieval': T.rag,
  'rag-evaluation': T.rag,
  'rag-production': T.rag,
  'rag-pitfalls': T.rag,
  'agent-basics': T.aiAgents,
  'agent-tools': T.aiAgents,
  'agent-planning': T.aiAgents,
  'vector-db': T.rag,
  embeddings: T.rag,
  'hybrid-search': T.rag,
  microservices: T.arch,
  'api-design': T.arch,
  caching: T.arch,
  auth: T.methodology,
  'data-privacy': T.methodology,
  'rate-limiting': T.methodology,
  monitoring: T.devops,
  'ci-cd': T.devops,
  'config-mgmt': T.devops,

  // ─── Prisma seed samples ───
  'typescript-generics-mastery': T.methodology,

  // ─── Growth / SEO ───
  'nextjs-seo-optimization': T.digitalOps,
};

/** Resolve CC20 section slug for a KB article slug. */
export function getCc20SectionSlugForArticle(articleSlug: string): string {
  return ARTICLE_CC20_SECTION[articleSlug] ?? CC20_DEFAULT_SECTION_SLUG;
}
