#!/usr/bin/env node
/**
 * Codcompass Knowledge Base Content Expansion
 * Usage: npx tsx scripts/seed-content-expansion.ts
 *
 * Categories follow Codcompass 2.0 taxonomy (lib/cc20-kb-taxonomy.ts).
 */
import { createClient } from '@supabase/supabase-js';
import crypto from 'crypto';
import {
  CC20_SECTIONS,
  getCc20SectionSlugForArticle,
} from '../lib/cc20-kb-taxonomy';

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

function uid() { return crypto.randomUUID(); }

const tagNames = [
  'hooks', 'state-management', 'performance', 'security', 'typescript',
  'api', 'testing', 'deployment', 'patterns', 'authentication',
  'server-components', 'responsive', 'animation', 'postgresql', 'docker',
  'ci-cd', 'machine-learning', 'ai', 'graphql', 'rest-api',
  'redis', 'mongodb', 'tailwind', 'web-components', 'pwa',
];

const articles = [
  // REACT
  { slug:'react-19-what-is-new', titleEn:'React 19: Everything You Need to Know', contentEn:'<h2>React 19: The Next Generation</h2><p>React 19 brings significant improvements to developer experience and runtime performance.</p><h3>Server Components by Default</h3><p>Components run on the server unless marked with <code>use client</code>.</p><h3>use() Hook</h3><p>Read promises or context directly:</p><pre><code>import { use } from \'react\';\nfunction UserProfile({ userId }) {\n  const user = use(fetchUser(userId));\n  return <div>{user.name}</div>;\n}</code></pre><h3>Actions</h3><p>Built-in form submission with automatic loading states.</p><h3>Document Metadata</h3><p>Components can return title and meta tags directly.</p><h3>Performance</h3><ul><li>25% faster hydration</li><li>Automatic server component memoization</li><li>15% smaller client bundle</li></ul>', excerptEn:'React 19 features: Server Components, Actions, use() hook, and performance improvements.', descriptionEn:'Learn about React 19 new features including Server Components, Actions, use() hook, and performance.', isPremium:false, categorySlug:'react', tagSlugs:['hooks','server-components','performance'] },
  { slug:'react-state-management-2026', titleEn:'React State Management in 2026: Complete Guide', contentEn:'<h2>State Management Landscape</h2><p>Choosing the right approach for your React app.</p><h3>Built-in: useState & useReducer</h3><p>For local component state, useState remains the go-to. For complex logic, useReducer provides predictable transitions.</p><h3>Context API</h3><p>Perfect for theme, auth, and language settings.</p><h3>Server State: TanStack Query</h3><pre><code>import { useQuery } from \'@tanstack/react-query\';\nfunction useTodos() {\n  return useQuery({ queryKey: [\'todos\'], queryFn: () => fetch(\'/api/todos\').then(r => r.json()), staleTime: 5*60*1000 });\n}</code></pre><h3>Global: Zustand</h3><pre><code>import { create } from \'zustand\';\nconst useStore = create((set) => ({ bears: 0, increase: () => set((s) => ({ bears: s.bears + 1 })) }));</code></pre><h3>Global: Jotai</h3><pre><code>import { atom, useAtom } from \'jotai\';\nconst countAtom = atom(0);</code></pre><h3>Decision Matrix</h3><table><tr><th>Use Case</th><th>Solution</th></tr><tr><td>Local state</td><td>useState / useReducer</td></tr><tr><td>API data</td><td>TanStack Query / SWR</td></tr><tr><td>Theme/Auth</td><td>Context API</td></tr><tr><td>Complex global</td><td>Zustand / Jotai</td></tr></table>', excerptEn:'React state management: useState, Context, TanStack Query, Zustand, Jotai.', descriptionEn:'Complete guide to React state management approaches in 2026.', isPremium:true, categorySlug:'react', tagSlugs:['state-management','patterns'] },
  { slug:'react-custom-hooks-patterns', titleEn:'Essential Custom Hook Patterns Every React Developer Should Know', contentEn:'<h2>Custom Hooks Patterns</h2><p>Extract and reuse stateful logic across components.</p><h3>useLocalStorage</h3><p>Persist state across page reloads with automatic JSON serialization.</p><h3>useDebounce</h3><p>Debounce rapid updates, perfect for search inputs.</p><h3>useIntersectionObserver</h3><p>Detect when elements enter the viewport for lazy loading and animations.</p><h3>useMediaQuery</h3><p>Responsive breakpoints in JavaScript using matchMedia.</p><h3>usePrevious</h3><p>Access the previous value of any state using refs.</p><h3>useAsync</h3><p>Handle async operations with loading and error states.</p>', excerptEn:'Custom hook patterns: useLocalStorage, useDebounce, useIntersectionObserver, useMediaQuery.', descriptionEn:'Essential custom hook patterns for React development.', isPremium:false, categorySlug:'react', tagSlugs:['hooks','patterns'] },
  { slug:'react-testing-guide', titleEn:'React Testing: Complete Guide with Vitest and Testing Library', contentEn:'<h2>Testing React Applications</h2><p>Ensure reliability with unit, integration, and E2E tests.</p><h3>Setup with Vitest</h3><pre><code>import { defineConfig } from \'vitest/config\';\nimport react from \'@vitejs/plugin-react\';\nexport default defineConfig({ plugins: [react()], test: { globals: true, environment: \'jsdom\' } });</code></pre><h3>Component Testing</h3><p>Test components as users would interact with them using Testing Library queries.</p><h3>Testing Hooks</h3><p>Use renderHook and act from Testing Library to test custom hooks.</p><h3>Best Practices</h3><ul><li>Test behavior, not implementation</li><li>Query priority: getByRole, getByLabelText, getByText</li><li>Mock external dependencies</li><li>Prefer integration over unit tests</li></ul>', excerptEn:'React testing with Vitest, Testing Library, and best practices.', descriptionEn:'Complete React testing guide.', isPremium:true, categorySlug:'react', tagSlugs:['testing','patterns'] },
  { slug:'react-error-boundaries', titleEn:'React Error Boundaries: Graceful Error Handling', contentEn:'<h2>Error Boundaries in React</h2><p>Catch errors and display fallback UI instead of crashing.</p><h3>Implementation</h3><p>Class components with getDerivedStateFromError and componentDidCatch can catch errors in their child tree.</p><h3>Usage</h3><pre><code>&lt;ErrorBoundary&gt;\n  <UserProfile userId={userId} />\n</ErrorBoundary></code></pre><h3>Best Practices</h3><ul><li>Wrap independent UI sections</li><li>Log to monitoring (Sentry, LogRocket)</li><li>Provide recovery (retry button)</li></ul>', excerptEn:'React error boundaries for graceful error handling and recovery.', descriptionEn:'Implement error boundaries in React.', isPremium:false, categorySlug:'react', tagSlugs:['patterns','security'] },
  { slug:'react-suspense-streaming', titleEn:'React Suspense and Streaming SSR', contentEn:'<h2>Suspense and Streaming SSR</h2><p>Transform page load experience with progressive rendering.</p><h3>Suspense</h3><p>Wrap components that load data with Suspense and provide fallback UI.</p><h3>Streaming SSR</h3><p>Stream HTML in chunks so critical content renders first while slower sections load independently.</p><h3>Benefits</h3><ul><li>Faster TTFB</li><li>Progressive loading</li><li>Better UX</li><li>Error isolation</li></ul>', excerptEn:'React Suspense and streaming SSR for faster page loads.', descriptionEn:'Master React Suspense and streaming server-side rendering.', isPremium:true, categorySlug:'react', tagSlugs:['server-components','performance'] },
  // TYPESCRIPT
  { slug:'typescript-5-deep-dive', titleEn:'TypeScript 5.x: New Features and Deep Dive', contentEn:'<h2>TypeScript 5.x Features</h2><p>Performance improvements and new language features.</p><h3>Decorators</h3><p>Stage 3 TC39 decorators are now supported for classes and methods.</p><h3>const Type Parameters</h3><p>Infer more specific types in generics with const type parameters.</p><h3>Performance</h3><p>--incremental and project references make builds significantly faster for large codebases.</p>', excerptEn:'TypeScript 5.x: decorators, const type parameters, and performance.', descriptionEn:'Explore TypeScript 5.x new features.', isPremium:false, categorySlug:'typescript', tagSlugs:['typescript','patterns'] },
  { slug:'typescript-utility-types', titleEn:'TypeScript Utility Types: Complete Reference', contentEn:'<h2>Utility Types</h2><p>Transform existing types with built-in utilities.</p><h3>Common Types</h3><pre><code>interface User { id: number; name: string; email: string; }\ntype Update = Partial<User>;           // all optional\ntype Name = Pick<User, \'name\' | \'email\'>; // select\ntype NoEmail = Omit<User, \'email\'>;     // exclude\ntype Perms = Record<string, string[]>;  // dictionary</code></pre><h3>Custom Utilities</h3><pre><code>type DeepPartial<T> = T extends object ? { [P in keyof T]?: DeepPartial<T[P]>; } : T;\ntype Nullable<T> = { [P in keyof T]: T[P] | null };\ntype DeepReadonly<T> = { readonly [P in keyof T]: T[P] extends object ? DeepReadonly<T[P]> : T[P]; };</code></pre>', excerptEn:'TypeScript utility types: Partial, Pick, Omit, Record, and custom utilities.', descriptionEn:'Master TypeScript utility types.', isPremium:false, categorySlug:'typescript', tagSlugs:['typescript'] },
  { slug:'typescript-generics-advanced', titleEn:'Advanced TypeScript Generics: Conditional and Mapped Types', contentEn:'<h2>Advanced Generics</h2><p>Conditional types, mapped types, and template literals.</p><h3>Conditional Types</h3><pre><code>type IsString<T> = T extends string ? true : false;\ntype Event = { type: \'click\'; x: number } | { type: \'keydown\'; key: string };</code></pre><h3>Mapped Types</h3><pre><code>type NullablePartial<T> = { [P in keyof T]?: T[P] | null; };\ntype Functions<T> = { [P in keyof T as T[P] extends Function ? P : never]: T[P]; };</code></pre><h3>Template Literal Types</h3><pre><code>type HandlerName = `on${Capitalize<\'click\' | \'hover\'>}`; // onClick | onHover</code></pre>', excerptEn:'Advanced TypeScript: conditional types, mapped types, template literals.', descriptionEn:'Learn advanced TypeScript generics.', isPremium:true, categorySlug:'typescript', tagSlugs:['typescript'] },
  { slug:'typescript-narrowing', titleEn:'TypeScript Type Narrowing: From Basic to Expert', contentEn:'<h2>Type Narrowing</h2><p>TypeScript narrows types within conditional blocks.</p><h3>typeof Guard</h3><pre><code>function padLeft(value: string, padding: string | number) {\n  if (typeof padding === \'number\') return \' \'.repeat(padding) + value;\n  return padding + value; // narrowed to string\n}</code></pre><h3>Custom Type Guards</h3><pre><code>function isAdmin(user: Admin | User): user is Admin {\n  return user.role === \'admin\';\n}</code></pre><h3>Discriminated Unions</h3><pre><code>type Result<T> = { success: true; data: T } | { success: false; error: string };</code></pre>', excerptEn:'TypeScript type narrowing: typeof guards, custom type guards, discriminated unions.', descriptionEn:'Learn TypeScript type narrowing techniques.', isPremium:false, categorySlug:'typescript', tagSlugs:['typescript'] },
  { slug:'typescript-migration-guide', titleEn:'Migrating JavaScript to TypeScript: Complete Strategy', contentEn:'<h2>JS to TS Migration</h2><p>Incremental migration strategy.</p><h3>Step 1: Enable allowJs</h3><p>Add TypeScript to your project while keeping JavaScript files.</p><h3>Step 2: Add JSDoc Types</h3><p>Start adding type annotations using JSDoc comments.</p><h3>Step 3: Rename to .ts</h3><p>Rename files incrementally, starting with utilities.</p><h3>Step 4: Enable Strict Mode</h3><p>Turn on strict, noImplicitAny, and strictNullChecks.</p>', excerptEn:'Step-by-step JavaScript to TypeScript migration strategy.', descriptionEn:'Learn incremental JS to TS migration.', isPremium:true, categorySlug:'typescript', tagSlugs:['typescript'] },
  // NEXT.JS
  { slug:'nextjs-15-app-router-complete', titleEn:'Next.js 15 App Router: Complete Guide', contentEn:'<h2>App Router</h2><p>The future of Next.js.</p><h3>File-Based Routing</h3><pre><code>app/\n├── layout.tsx      # Root layout\n├── page.tsx        # Home\n├── loading.tsx     # Loading UI\n├── error.tsx       # Error boundary\n├── blog/[slug]/page.tsx # Dynamic route</code></pre><h3>Server Components</h3><p>Components are server components by default. Fetch data directly in components.</p><h3>Client Components</h3><p>Add <code>use client</code> directive for interactivity (useState, useEffect, event handlers).</p><h3>Data Fetching</h3><p>Use fetch with cache options: no-store, force-cache, or revalidate intervals.</p><h3>Metadata API</h3><p>Export metadata object or generateMetadata function for SEO.</p>', excerptEn:'Next.js 15 App Router: server components, data fetching, routing, and metadata.', descriptionEn:'Master the Next.js 15 App Router.', isPremium:false, categorySlug:'nextjs', tagSlugs:['server-components','patterns'] },
  { slug:'nextjs-api-routes', titleEn:'Next.js API Routes: Building RESTful Backends', contentEn:'<h2>API Routes in Next.js 15</h2><p>Build full-stack apps with API routes.</p><h3>Basic Route</h3><pre><code>export async function GET() {\n  const posts = await db.post.findMany();\n  return NextResponse.json(posts);\n}\nexport async function POST(request: Request) {\n  const body = await request.json();\n  return NextResponse.json(await db.post.create({ data: body }), { status: 201 });\n}</code></pre><h3>Dynamic Routes</h3><p>Use [id] folders for dynamic parameters.</p><h3>Middleware</h3><p>Protect routes with middleware for authentication and validation.</p>', excerptEn:'Build RESTful APIs with Next.js 15 API routes, middleware, and authentication.', descriptionEn:'Learn Next.js API routes.', isPremium:true, categorySlug:'nextjs', tagSlugs:['api','rest-api','security'] },
  { slug:'nextjs-seo-optimization', titleEn:'Next.js SEO: Complete Optimization Guide', contentEn:'<h2>SEO in Next.js</h2><p>Maximize search engine visibility.</p><h3>Metadata API</h3><pre><code>export const metadata: Metadata = {\n  title: { default: \'My App\', template: \'%s | My App\' },\n  description: \'Description here\',\n  openGraph: { title: \'My App\', images: [\'/og.jpg\'] },\n  twitter: { card: \'summary_large_image\' },\n};</code></pre><h3>Dynamic Metadata</h3><p>Use generateMetadata for per-page titles and descriptions.</p><h3>Sitemap & Robots</h3><p>Export sitemap and robots functions from app/sitemap.ts and app/robots.ts.</p>', excerptEn:'Next.js SEO: Metadata API, Open Graph, Twitter Cards, sitemaps.', descriptionEn:'Master Next.js SEO optimization.', isPremium:false, categorySlug:'nextjs', tagSlugs:['performance','patterns'] },
  { slug:'nextjs-authentication', titleEn:'Next.js Authentication: NextAuth.js v5 Complete Guide', contentEn:'<h2>Authentication in Next.js</h2><p>NextAuth.js v5 provides flexible authentication.</p><h3>Setup</h3><pre><code>import NextAuth from \'next-auth\';\nimport GitHub from \'next-auth/providers/github\';\nexport const { handlers, auth } = NextAuth({\n  providers: [GitHub({ clientId: process.env.GITHUB_ID, clientSecret: process.env.GITHUB_SECRET })],\n});</code></pre><h3>Protecting Routes</h3><p>Export auth as middleware and configure matcher for protected paths.</p><h3>Server Components</h3><p>Call auth() in server components to get the current session.</p>', excerptEn:'Next.js authentication with NextAuth.js v5: providers, middleware, sessions.', descriptionEn:'Implement authentication in Next.js.', isPremium:true, categorySlug:'nextjs', tagSlugs:['authentication','security'] },
  { slug:'nextjs-performance', titleEn:'Next.js Performance: Optimization Techniques for 2026', contentEn:'<h2>Performance Optimization</h2><p>Make your Next.js app blazing fast.</p><h3>Image Optimization</h3><pre><code>import Image from \'next/image\';\n<Image src="/hero.jpg" width={1200} height={600} priority quality={75} /></code></pre><h3>Font Optimization</h3><p>Use next/font/google for automatic font optimization with zero layout shift.</p><h3>Caching</h3><p>Configure fetch cache: no-store for real-time, revalidate for stale-while-revalidate.</p><h3>Route Config</h3><pre><code>export const dynamic = \'force-static\'; // or force-dynamic\nexport const runtime = \'edge\'; // for low latency</code></pre>', excerptEn:'Next.js performance: Image, Font, caching, and route optimization.', descriptionEn:'Master Next.js performance optimization.', isPremium:true, categorySlug:'nextjs', tagSlugs:['performance'] },
  // JAVASCRIPT
  { slug:'javascript-es2026-features', titleEn:'JavaScript ES2026: New Features You Should Know', contentEn:'<h2>ES2026 Features</h2><p>JavaScript continues to evolve.</p><h3>Array Grouping</h3><pre><code>const scores = [85, 92, 78, 95, 88];\nconst grouped = Object.groupBy(scores, s => s >= 90 ? \'A\' : s >= 80 ? \'B\' : \'C\');</code></pre><h3>Promise.withResolvers</h3><pre><code>const { promise, resolve } = Promise.withResolvers();\nsetTimeout(() => resolve(\'done\'), 1000);</code></pre><h3>findLast</h3><pre><code>[1,2,3,4,5].findLast(n => n > 2); // 5</code></pre><h3>structuredClone</h3><pre><code>const copy = structuredClone(original);</code></pre>', excerptEn:'JavaScript ES2026: array grouping, Promise.withResolvers, findLast, structuredClone.', descriptionEn:'Latest JavaScript features.', isPremium:false, categorySlug:'javascript', tagSlugs:['patterns'] },
  { slug:'javascript-async-patterns', titleEn:'JavaScript Async Patterns: Beyond async/await', contentEn:'<h2>Advanced Async Patterns</h2><p>Master asynchronous programming.</p><h3>Promise.all vs allSettled</h3><p>all fails fast. allSettled waits for all promises regardless of success.</p><h3>Promise.any and race</h3><p>any resolves with first fulfilled. race resolves with first settled.</p><h3>Async Iterators</h3><pre><code>async function* readLines(path) {\n  const file = await open(path);\n  for await (const line of file) yield line.trim();\n}</code></pre><h3>AbortController</h3><p>Cancel fetch requests and other async operations.</p>', excerptEn:'Advanced JavaScript async patterns: Promise.allSettled, any, race, async iterators.', descriptionEn:'Master JavaScript async patterns.', isPremium:true, categorySlug:'javascript', tagSlugs:['patterns'] },
  { slug:'javascript-event-loop', titleEn:'Understanding the JavaScript Event Loop', contentEn:'<h2>The Event Loop</h2><p>JavaScript is single-threaded. The event loop handles async operations.</p><h3>How It Works</h3><ol><li>Call Stack: executes sync code</li><li>Web APIs: handle async (setTimeout, fetch)</li><li>Microtask Queue: Promises (high priority)</li><li>Callback Queue: setTimeout callbacks</li></ol><h3>Execution Order</h3><pre><code>console.log(\'1\');\nsetTimeout(() => console.log(\'2\'), 0);\nPromise.resolve().then(() => console.log(\'3\'));\nconsole.log(\'4\');\n// Output: 1, 4, 3, 2</code></pre><h3>Best Practices</h3><ul><li>Avoid blocking the main thread</li><li>Use Web Workers for CPU-intensive tasks</li><li>Batch DOM updates with requestAnimationFrame</li></ul>', excerptEn:'JavaScript event loop: call stack, queues, execution order.', descriptionEn:'Understand the JavaScript event loop.', isPremium:false, categorySlug:'javascript', tagSlugs:['performance'] },
  { slug:'javascript-modules-guide', titleEn:'JavaScript Modules: CommonJS, ESM, and Beyond', contentEn:'<h2>JavaScript Modules</h2><p>Understand module systems.</p><h3>ES Modules</h3><pre><code>export const PI = 3.14159;\nexport function area(r) { return PI * r * r; }\nexport default class Calculator {}</code></pre><h3>Dynamic Imports</h3><pre><code>const module = await import(\'./heavy-module.js\');\nmodule.doSomething();</code></pre><p>Use for code splitting and conditional loading.</p>', excerptEn:'JavaScript modules: ESM, CommonJS, dynamic imports, code splitting.', descriptionEn:'Learn JavaScript module systems.', isPremium:false, categorySlug:'javascript', tagSlugs:['patterns'] },
  // CSS
  { slug:'css-container-queries', titleEn:'CSS Container Queries: The Future of Responsive Design', contentEn:'<h2>Container Queries</h2><p>Components respond to their parent size, not just viewport.</p><h3>Basic Usage</h3><pre><code>.card-container {\n  container-type: inline-size;\n  container-name: card;\n}\n@container card (min-width: 400px) {\n  .card { display: grid; grid-template-columns: 200px 1fr; }\n}</code></pre><h3>Container Units</h3><pre><code>.text { font-size: calc(1rem + 2cqw); }</code></pre>', excerptEn:'CSS container queries for component-level responsive design.', descriptionEn:'Learn CSS container queries.', isPremium:false, categorySlug:'css', tagSlugs:['responsive'] },
  { slug:'css-animations-2026', titleEn:'CSS Animations in 2026: New Features and Techniques', contentEn:'<h2>CSS Animations</h2><p>Modern CSS animation capabilities.</p><h3>View Transitions API</h3><pre><code>document.startViewTransition(() => element.classList.toggle(\'expanded\'));</code></pre><h3>Scroll-Driven Animations</h3><pre><code>.progress-bar {\n  animation: progress auto linear;\n  animation-timeline: scroll();\n}</code></pre><h3>@property</h3><pre><code>@property --angle { syntax: \'<angle>\'; initial-value: 0deg; }\n@keyframes rotate { to { --angle: 360deg; } }</code></pre>', excerptEn:'CSS animations: View Transitions, scroll-driven animations, @property.', descriptionEn:'Modern CSS animation techniques.', isPremium:true, categorySlug:'css', tagSlugs:['animation'] },
  { slug:'tailwind-css-best-practices', titleEn:'Tailwind CSS v4: Best Practices and New Features', contentEn:'<h2>Tailwind CSS v4</h2><p>New engine, CSS-first configuration, improved performance.</p><h3>CSS-First Config</h3><pre><code>@import "tailwindcss";\n@theme {\n  --color-primary: #3b82f6;\n  --font-display: "Inter", sans-serif;\n}</code></pre><h3>New Features</h3><ul><li>Zero-config setup</li><li>CSS-first configuration</li><li>10x faster builds (Rust engine)</li><li>Built-in container query support</li></ul>', excerptEn:'Tailwind CSS v4: CSS-first config, new engine, container queries.', descriptionEn:'Learn Tailwind CSS v4.', isPremium:false, categorySlug:'css', tagSlugs:['tailwind','patterns'] },
  { slug:'css-grid-layout', titleEn:'CSS Grid Layout: Complete Guide', contentEn:'<h2>CSS Grid</h2><p>The most powerful CSS layout system.</p><h3>Responsive Grid</h3><pre><code>.grid {\n  display: grid;\n  grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));\n  gap: 1.5rem;\n}</code></pre><h3>Subgrid</h3><pre><code>.card {\n  display: grid;\n  grid-template-rows: subgrid;\n  grid-row: span 3;\n}</code></pre>', excerptEn:'CSS Grid: responsive layouts, subgrid, auto-placement.', descriptionEn:'Master CSS Grid Layout.', isPremium:false, categorySlug:'css', tagSlugs:['responsive','patterns'] },
  // AI/ML
  { slug:'ai-rag-complete-guide', titleEn:'RAG: Retrieval-Augmented Generation Complete Guide', contentEn:'<h2>RAG Architecture</h2><p>Combine retrieval from your knowledge base with AI generation.</p><h3>Three Steps</h3><ol><li><strong>Index:</strong> Chunk documents, create embeddings, store in vector DB</li><li><strong>Retrieve:</strong> Convert query to embedding, find similar chunks</li><li><strong>Generate:</strong> Send chunks + query to LLM</li></ol><h3>Implementation</h3><pre><code>const embeddings = new OpenAIEmbeddings();\nconst store = await MemoryVectorStore.fromDocuments(docs, embeddings);\nconst results = await store.similaritySearch(\'query\', 3);\nconst prompt = `Context: ${results.map(r => r.pageContent).join(\'\\n\')}\\nQuestion: {query}`;\nconst response = await llm.invoke(prompt);</code></pre><h3>Chunking Strategies</h3><ul><li>Fixed-size: 500-1000 chars</li><li>Semantic: paragraph boundaries</li><li>Recursive: paragraphs then sentences</li></ul>', excerptEn:'RAG guide: architecture, LangChain implementation, chunking strategies.', descriptionEn:'Build RAG applications for AI-powered search.', isPremium:true, categorySlug:'ai-ml', tagSlugs:['ai'] },
  { slug:'ai-fine-tuning-guide', titleEn:'Fine-Tuning LLMs: A Practical Guide', contentEn:'<h2>Fine-Tuning LLMs</h2><p>Adapt pre-trained models to your domain.</p><h3>When to Fine-Tune</h3><ul><li>Need consistent output format</li><li>Need domain-specific knowledge</li><li>Prompt engineering insufficient</li></ul><h3>LoRA</h3><pre><code>from peft import LoraConfig, get_peft_model\nconfig = LoraConfig(r=16, lora_alpha=32, target_modules=["q_proj", "v_proj"])\nmodel = get_peft_model(base_model, config)</code></pre><h3>Dataset Format</h3><pre><code>[{"instruction": "Summarize", "input": "text...", "output": "summary..."}]</code></pre>', excerptEn:'Fine-tune LLMs with LoRA, prepare datasets, evaluate performance.', descriptionEn:'Practical guide to fine-tuning LLMs.', isPremium:true, categorySlug:'ai-ml', tagSlugs:['ai','machine-learning'] },
  { slug:'ai-agents-langchain', titleEn:'Building AI Agents with LangChain', contentEn:'<h2>AI Agents</h2><p>Agents use tools, reason, and take actions autonomously.</p><h3>Basic Agent</h3><pre><code>import { initializeAgentExecutorWithOptions } from \'langchain/agents\';\nimport { Calculator } from \'langchain/tools/calculator\';\nconst executor = await initializeAgentExecutorWithOptions(\n  [new Calculator()], llm, { agentType: \'openai-functions\' }\n);\nconst result = await executor.run(\'What is 25 * 42 + 17?\');</code></pre><h3>Custom Tools</h3><pre><code>const searchTool = tool(async (q) => searchAPI(q), { name: \'search\', description: \'Search KB\' });</code></pre>', excerptEn:'Build AI agents with LangChain: tools, chains, autonomous agents.', descriptionEn:'Learn to build AI agents.', isPremium:true, categorySlug:'ai-ml', tagSlugs:['ai'] },
  { slug:'ai-vector-databases', titleEn:'Vector Databases for AI: Pinecone vs Weaviate vs pgvector', contentEn:'<h2>Vector Databases</h2><p>Store and search embeddings for AI apps.</p><h3>Comparison</h3><table><tr><th>Feature</th><th>Pinecone</th><th>Weaviate</th><th>pgvector</th></tr><tr><td>Type</td><td>Cloud</td><td>Cloud + Self</td><td>PostgreSQL</td></tr><tr><td>Free Tier</td><td>Yes</td><td>Yes</td><td>Yes</td></tr><tr><td>Hybrid Search</td><td>No</td><td>Yes</td><td>Yes</td></tr></table><h3>pgvector</h3><p>Best choice if you already use PostgreSQL. Add vector columns and similarity search to your existing database.</p>', excerptEn:'Vector DB comparison: Pinecone, Weaviate, pgvector.', descriptionEn:'Choose the right vector database for AI.', isPremium:false, categorySlug:'ai-ml', tagSlugs:['ai','postgresql'] },
  // DEVOPS
  { slug:'docker-compose-guide', titleEn:'Docker Compose: Complete Guide for Development', contentEn:'<h2>Docker Compose</h2><p>Multi-container Docker applications made simple.</p><h3>Basic compose.yml</h3><pre><code>services:\n  web:\n    build: .\n    ports: ["3000:3000"]\n    volumes: [".:/app"]\n    depends_on: [db, redis]\n  db:\n    image: postgres:16\n    environment:\n      POSTGRES_DB: myapp\n      POSTGRES_PASSWORD: secret\n    volumes: [pgdata:/var/lib/postgresql/data]\n  redis:\n    image: redis:7-alpine\nvolumes:\n  pgdata:</code></pre><h3>Multi-Stage Builds</h3><pre><code>FROM node:20 AS builder\nWORKDIR /app\nCOPY . .\nRUN npm ci && npm run build\n\nFROM node:20-alpine\nCOPY --from=builder /app/dist /app/dist\nCMD ["node", "dist/index.js"]</code></pre>', excerptEn:'Docker Compose: multi-container apps, volumes, multi-stage builds.', descriptionEn:'Master Docker Compose for development.', isPremium:false, categorySlug:'devops', tagSlugs:['docker'] },
  { slug:'github-actions-ci-cd', titleEn:'GitHub Actions: CI/CD Pipeline Complete Guide', contentEn:'<h2>GitHub Actions</h2><p>Automate your development workflow.</p><h3>Basic Pipeline</h3><pre><code>name: CI\non: [push, pull_request]\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-node@v4\n        with: { node-version: 20 }\n      - run: npm ci\n      - run: npm test\n      - run: npm run build</code></pre><h3>Deployment</h3><pre><code>  deploy:\n    needs: test\n    runs-on: ubuntu-latest\n    if: github.ref == \'refs/heads/main\'\n    steps:\n      - uses: actions/checkout@v4\n      - uses: amondnet/vercel-action@v25\n        with: { vercel-token: ${{ secrets.VERCEL_TOKEN }} }</code></pre>', excerptEn:'GitHub Actions: CI/CD pipelines, testing, deployment automation.', descriptionEn:'Learn GitHub Actions for CI/CD.', isPremium:false, categorySlug:'devops', tagSlugs:['ci-cd','deployment'] },
  { slug:'linux-essentials-devops', titleEn:'Linux Essentials Every Developer Should Know', contentEn:'<h2>Linux for Developers</h2><p>Essential commands and concepts.</p><h3>File Operations</h3><pre><code>ls -la          # List all files with details\ncp -r src/ dest/ # Copy directory\nmv old new      # Move/rename\nfind . -name "*.ts"  # Find files\ngrep -r "TODO" src/  # Search in files</code></pre><h3>Process Management</h3><pre><code>ps aux          # List processes\nkill -9 PID     # Kill process\ntop             # System monitor\nsystemctl status nginx  # Service status</code></pre><h3>Networking</h3><pre><code>curl -I https://example.com  # Headers\nssh user@host               # Remote login\nscp file user@host:/path    # Copy files</code></pre>', excerptEn:'Linux essentials: file operations, process management, networking.', descriptionEn:'Essential Linux commands for developers.', isPremium:false, categorySlug:'devops', tagSlugs:['deployment'] },
  { slug:'monitoring-observability', titleEn:'Application Monitoring and Observability', contentEn:'<h2>Observability</h2><p>Three pillars: Logs, Metrics, Traces.</p><h3>Logging</h3><pre><code>import winston from \'winston\';\nconst logger = winston.createLogger({\n  level: \'info\',\n  format: winston.format.json(),\n  transports: [new winston.transports.File({ filename: \'app.log\' })]\n});</code></pre><h3>Health Checks</h3><pre><code>app.get(\'/health\', (req, res) => {\n  res.json({ status: \'ok\', uptime: process.uptime(), memory: process.memoryUsage() });\n});</code></pre><h3>APM Tools</h3><p>Datadog, New Relic, Sentry, Grafana + Prometheus for full observability.</p>', excerptEn:'Application monitoring: logging, metrics, traces, health checks.', descriptionEn:'Learn observability best practices.', isPremium:true, categorySlug:'devops', tagSlugs:['deployment','patterns'] },
  // NODE.JS
  { slug:'nodejs-best-practices', titleEn:'Node.js Best Practices for Production', contentEn:'<h2>Node.js Production</h2><p>Run Node.js reliably in production.</p><h3>Error Handling</h3><pre><code>process.on(\'uncaughtException\', (err) => {\n  logger.error(\'Uncaught:\', err);\n  process.exit(1);\n});\nprocess.on(\'unhandledRejection\', (reason) => {\n  logger.error(\'Unhandled rejection:\', reason);\n});</code></pre><h3>Cluster Mode</h3><p>Use all CPU cores with the cluster module or PM2.</p><h3>Environment Variables</h3><pre><code>import dotenv from \'dotenv\';\ndotenv.config();\nconst config = {\n  port: parseInt(process.env.PORT || \'3000\'),\n  dbUrl: process.env.DATABASE_URL,\n};</code></pre>', excerptEn:'Node.js production: error handling, clustering, environment config.', descriptionEn:'Node.js best practices for production.', isPremium:false, categorySlug:'nodejs', tagSlugs:['patterns','deployment'] },
  { slug:'nodejs-rest-api', titleEn:'Building REST APIs with Node.js and Express', contentEn:'<h2>REST APIs</h2><p>Build robust APIs with Express.</p><h3>Basic Server</h3><pre><code>import express from \'express\';\nconst app = express();\napp.use(express.json());\n\napp.get(\'/api/posts\', async (req, res) => {\n  const posts = await db.post.findMany();\n  res.json(posts);\n});\n\napp.post(\'/api/posts\', async (req, res) => {\n  const post = await db.post.create({ data: req.body });\n  res.status(201).json(post);\n});\n\napp.listen(3000);</code></pre><h3>Error Middleware</h3><pre><code>app.use((err, req, res, next) => {\n  logger.error(err);\n  res.status(500).json({ error: \'Internal server error\' });\n});</code></pre>', excerptEn:'REST API with Node.js and Express: routes, middleware, error handling.', descriptionEn:'Build REST APIs with Node.js.', isPremium:false, categorySlug:'nodejs', tagSlugs:['api','rest-api'] },
  { slug:'nodejs-streams', titleEn:'Node.js Streams: Processing Large Data Efficiently', contentEn:'<h2>Streams in Node.js</h2><p>Process data chunk by chunk without loading everything into memory.</p><h3>Readable Stream</h3><pre><code>import fs from \'fs\';\nfs.createReadStream(\'large-file.txt\')\n  .on(\'data\', (chunk) => console.log(\`Got ${chunk.length} bytes\`))\n  .on(\'end\', () => console.log(\'Done\'));</code></pre><h3>Piping</h3><pre><code>fs.createReadStream(\'input.txt\')\n  .pipe(transformStream)\n  .pipe(fs.createWriteStream(\'output.txt\'));</code></pre><h3>Use Cases</h3><p>File processing, API responses, real-time data, video/audio streaming.</p>', excerptEn:'Node.js streams: readable, writable, transform, piping.', descriptionEn:'Process large data efficiently with Node.js streams.', isPremium:true, categorySlug:'nodejs', tagSlugs:['patterns'] },
  // DATABASE
  { slug:'postgresql-performance', titleEn:'PostgreSQL Performance: Indexing and Query Optimization', contentEn:'<h2>PostgreSQL Performance</h2><p>Make your queries fly.</p><h3>Indexing</h3><pre><code>-- B-tree index (default)\nCREATE INDEX idx_users_email ON users(email);\n\n-- Composite index\nCREATE INDEX idx_posts_status_created ON posts(status, created_at);\n\n-- Partial index\nCREATE INDEX idx_active_users ON users(email) WHERE status = \'active\';\n\n-- GIN index for JSON/Full-text\nCREATE INDEX idx_docs_content ON docs USING GIN(content_jsonb);</code></pre><h3>EXPLAIN ANALYZE</h3><pre><code>EXPLAIN ANALYZE SELECT * FROM posts WHERE status = \'published\' ORDER BY created_at DESC;</code></pre><h3>Connection Pooling</h3><p>Use PgBouncer or Supavisor for connection pooling in production.</p>', excerptEn:'PostgreSQL performance: indexing, EXPLAIN ANALYZE, connection pooling.', descriptionEn:'Optimize PostgreSQL queries and performance.', isPremium:false, categorySlug:'database', tagSlugs:['postgresql','performance'] },
  { slug:'database-design-patterns', titleEn:'Database Design Patterns for Modern Apps', contentEn:'<h2>Database Design</h2><p>Design schemas that scale.</p><h3>Normalization</h3><p>1NF: atomic values. 2NF: no partial dependencies. 3NF: no transitive dependencies.</p><h3>When to Denormalize</h3><p>Read-heavy apps benefit from denormalization for query performance.</p><h3>Soft Deletes</h3><pre><code>ALTER TABLE posts ADD COLUMN deleted_at TIMESTAMP NULL;\n-- Filter: WHERE deleted_at IS NULL</code></pre><h3>Audit Trail</h3><pre><code>ALTER TABLE posts ADD COLUMN created_at TIMESTAMP DEFAULT NOW();\nALTER TABLE posts ADD COLUMN updated_at TIMESTAMP DEFAULT NOW();</code></pre>', excerptEn:'Database design: normalization, denormalization, soft deletes, audit trails.', descriptionEn:'Modern database design patterns.', isPremium:false, categorySlug:'database', tagSlugs:['patterns'] },
  { slug:'redis-caching-strategies', titleEn:'Redis Caching Strategies for Web Applications', contentEn:'<h2>Redis Caching</h2><p>Speed up your app with caching.</p><h3>Cache-Aside</h3><pre><code>async function getUser(id) {\n  const cached = await redis.get(\`user:${id}\`);\n  if (cached) return JSON.parse(cached);\n  const user = await db.user.findUnique({ where: { id } });\n  await redis.set(\`user:${id}\`, JSON.stringify(user), \'EX\', 3600);\n  return user;\n}</code></pre><h3>Strategies</h3><ul><li>Cache-Aside: lazy loading</li><li>Write-Through: update cache on write</li><li>Write-Behind: async cache update</li><li>TTL: expire after time</li></ul>', excerptEn:'Redis caching: cache-aside, write-through, TTL strategies.', descriptionEn:'Implement Redis caching for web apps.', isPremium:true, categorySlug:'database', tagSlugs:['redis','performance'] },
  { slug:'mongodb-vs-postgresql', titleEn:'MongoDB vs PostgreSQL: When to Use Each', contentEn:'<h2>MongoDB vs PostgreSQL</h2><p>Choosing the right database.</p><h3>PostgreSQL: Choose When</h3><ul><li>Relational data with complex joins</li><li>ACID transactions required</li><li>Structured schema</li><li>Complex queries and aggregations</li></ul><h3>MongoDB: Choose When</h3><ul><li>Flexible/unstructured schema</li><li>Document-based data</li><li>High write throughput</li><li>Horizontal scaling needed</li></ul><h3>Use Both</h3><p>Many apps use PostgreSQL for core data and MongoDB for logs/analytics.</p>', excerptEn:'MongoDB vs PostgreSQL: comparison and use cases.', descriptionEn:'Choose between MongoDB and PostgreSQL.', isPremium:false, categorySlug:'database', tagSlugs:['postgresql','mongodb'] },
  // SECURITY
  { slug:'web-security-essentials', titleEn:'Web Security Essentials Every Developer Should Know', contentEn:'<h2>Web Security</h2><p>Protect your applications from common attacks.</p><h3>XSS Prevention</h3><p>Sanitize user input, use Content Security Policy headers, avoid dangerouslySetInnerHTML.</p><h3>CSRF Protection</h3><p>Use anti-CSRF tokens, SameSite cookie attribute, verify Origin header.</p><h3>SQL Injection</h3><p>Use parameterized queries or ORM. Never concatenate user input into SQL.</p><h3>Security Headers</h3><pre><code>Content-Security-Policy: default-src \'self\'\nX-Frame-Options: DENY\nX-Content-Type-Options: nosniff\nStrict-Transport-Security: max-age=31536000</code></pre>', excerptEn:'Web security: XSS, CSRF, SQL injection, security headers.', descriptionEn:'Essential web security practices.', isPremium:false, categorySlug:'security', tagSlugs:['security'] },
  { slug:'jwt-authentication', titleEn:'JWT Authentication: Best Practices and Pitfalls', contentEn:'<h2>JWT Authentication</h2><p>Secure token-based authentication.</p><h3>Structure</h3><p>Header (algorithm, type) + Payload (claims) + Signature = JWT</p><h3>Best Practices</h3><ul><li>Short expiry (15min access, 7d refresh)</li><li>Store access token in memory, refresh in httpOnly cookie</li><li>Always use HTTPS</li><li>Validate signature and expiry</li><li>Don\'t store sensitive data in payload</li></ul><h3>Implementation</h3><pre><code>import jwt from \'jsonwebtoken\';\nconst token = jwt.sign({ userId: user.id }, process.env.JWT_SECRET, { expiresIn: \'15m\' });</code></pre>', excerptEn:'JWT authentication: best practices, token management, security.', descriptionEn:'Implement JWT authentication securely.', isPremium:true, categorySlug:'security', tagSlugs:['authentication','security'] },
  { slug:'api-security-guide', titleEn:'API Security: Rate Limiting, CORS, and Authentication', contentEn:'<h2>API Security</h2><p>Protect your APIs from abuse.</p><h3>Rate Limiting</h3><pre><code>import rateLimit from \'express-rate-limit\';\nconst limiter = rateLimit({\n  windowMs: 15 * 60 * 1000,\n  max: 100,\n  message: \'Too many requests\',\n});\napp.use(\'/api/\', limiter);</code></pre><h3>CORS</h3><pre><code>import cors from \'cors\';\napp.use(cors({ origin: \'https://yourdomain.com\', credentials: true }));</code></pre><h3>API Keys</h3><p>Generate unique API keys, store hashed, validate on each request.</p>', excerptEn:'API security: rate limiting, CORS, API keys, authentication.', descriptionEn:'Secure your APIs with rate limiting, CORS, and authentication.', isPremium:false, categorySlug:'security', tagSlugs:['security','api'] },
  { slug:'oauth2-guide', titleEn:'OAuth 2.0 and OpenID Connect: Complete Guide', contentEn:'<h2>OAuth 2.0 & OIDC</h2><p>Industry-standard authorization.</p><h3>Flows</h3><ul><li>Authorization Code + PKCE: SPAs and mobile apps</li><li>Client Credentials: server-to-server</li><li>Device Code: IoT and limited input devices</li></ul><h3>OIDC Adds</h3><p>Identity layer on top of OAuth 2.0 with ID tokens and user info endpoint.</p><h3>Implementation</h3><p>Use established libraries (NextAuth, Auth0, Clerk) rather than rolling your own.</p>', excerptEn:'OAuth 2.0 and OpenID Connect: flows, PKCE, implementation.', descriptionEn:'Learn OAuth 2.0 and OIDC for authentication.', isPremium:true, categorySlug:'security', tagSlugs:['authentication','security'] },
];

// ─── Seed Function ───
async function seed() {
  console.log('\n🌱 Codcompass Content Expansion');
  console.log('═'.repeat(50));

  // 1. Upsert CC20 categories
  console.log('\n📁 Categories (Codcompass 2.0)...');
  const catIdMap: Record<string, string> = {};
  for (let i = 0; i < CC20_SECTIONS.length; i++) {
    const cat = CC20_SECTIONS[i];
    const { data: existing } = await supabase.from('Category').select('id').eq('slug', cat.slug).maybeSingle();
    const id = existing?.id || uid();
    const { error } = await supabase.from('Category').upsert(
      {
        id,
        slug: cat.slug,
        name: cat.name,
        nameEn: cat.name,
        description: cat.descriptionEn,
        order: i + 1,
      },
      { onConflict: 'slug' }
    );
    if (error) console.log(`  ❌ ${cat.slug}: ${error.message}`);
    else {
      console.log(`  ✅ ${cat.slug}`);
      catIdMap[cat.slug] = id;
    }
  }

  // 2. Upsert tags
  console.log('\n🏷️  Tags...');
  const tagIdMap: Record<string, string> = {};
  for (const name of tagNames) {
    const slug = name.toLowerCase().replace(/[^a-z0-9]+/g, '-');
    const { data: existing } = await supabase.from('Tag').select('id').eq('slug', slug).single();
    const id = existing?.id || uid();
    const { error } = await supabase.from('Tag').upsert({ id, slug, name, nameEn: name }, { onConflict: 'slug' });
    if (error) console.log(`  ❌ ${name}`);
    else { console.log(`  ✅ ${name}`); tagIdMap[slug] = id; }
  }

  // 3. Insert articles
  console.log(`\n📝 Articles (${articles.length})...`);
  let ok = 0, fail = 0;

  for (const a of articles) {
    // Check if exists
    const { data: existing } = await supabase.from('Article').select('id').eq('slug', a.slug).single();
    const id = existing?.id || uid();

    const now = new Date().toISOString();
    const { error } = await supabase
      .from('Article')
      .upsert({
        id,
        slug: a.slug,
        titleEn: a.titleEn,
        contentEn: a.contentEn,
        excerptEn: a.excerptEn,
        descriptionEn: a.descriptionEn,
        isPremium: a.isPremium,
        isPublished: true,
        publishedAt: now,
        updatedAt: now,
      }, { onConflict: 'slug' });

    if (error) { console.log(`  ❌ ${a.slug}: ${error.message}`); fail++; continue; }
    ok++;
    console.log(`  ✅ ${a.slug}`);

    // Link category (CC20 section from slug mapping)
    const sectionSlug = getCc20SectionSlugForArticle(a.slug);
    const catId = catIdMap[sectionSlug];
    if (catId) {
      await supabase.from('_ArticleToCategory').delete().eq('A', id);
      await supabase.from('_ArticleToCategory').insert({ A: id, B: catId });
    }
    // Link tags
    for (const tagSlug of a.tagSlugs) {
      const tagId = tagIdMap[tagSlug];
      if (tagId) {
        await supabase.from('ArticleToTag').upsert(
          { articleId: id, tagId }, { onConflict: 'articleId,tagId' }
        );
      }
    }
  }

  console.log('\n' + '═'.repeat(50));
  console.log(`✅ Done! ${ok} success, ${fail} failed`);
  console.log(`📊 Total articles in KB: ${ok + 8} (including existing)`);
}

seed().catch((e) => { console.error(e); process.exit(1); });
